### ISSUE TITLE
数据分析

### ISSUE THREAD

**Issue by zerocoolys** [zerocoolys/relog#2]
1. host-> url + domain 2个字段存储
2. 新老访客的数据统计（cookie后端处理还是js前端就判断）
3. IP 直接 转换成地域
4. 新老客户的标识

**Comment by conchz** [comment]
1. host是指服务器本机, 只能获取IP
   2+4. 新老访客的数据统计和标识在前端处理（前端无法正常处理后端写回的cookie）
2. IP地址已经转换
